title: Orestis Papadopoulos
author: Orestis Papadopoulos
email: orjpap@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  I'm Orestis Papadopoulos. I work as a software developer.
  This is my blog, I write about software, sounds and Swift.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Orestis Papadopoulos
  tagline: Sound, Software, Swift
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: OrestisPapadop8
    github:  orjpap
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
  navigation: true

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed